namespace YukkuriMovieMaker.Plugin.Community.Shape.Pen
{
    enum PenLayerBlendMode
    {
        Normal,
        Multiply,
        Screen,
        Darken,
        Lighten,
        Dissolve,
        ColorBurn,
        LinearBurn,
        DarkerColor,
        LighterColor,
        ColorDodge,
        LinearDodge,
        Overlay,
        SoftLight,
        HardLight,
        VividLight,
        LinearLight,
        PinLight,
        HardMix,
        Difference,
        Exclusion,
        Hue,
        Saturation,
        Color,
        Luminosity,
        Subtract,
        Division,
    }
}
